services:
  - type: web
    name: django-web-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn afd-backend.wsgi"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db.sqlite3
          property: connectionString
      - key: 123456
        sync: false
        value: your-secret-key
      - key: ALLOWED_HOSTS
        sync: false
        value: afd-platform.com
