services:
  - type: web
    name: django-web-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn config.wsgi"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: "*"
