# Generated by Django 4.2.17 on 2024-12-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=512)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Add_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_preview', models.FileField(blank=True, null=True, upload_to='movies_images')),
                ('movies_preview_url', models.CharField(blank=True, max_length=5024, null=True)),
                ('movies_name', models.CharField(max_length=128)),
                ('movies_description', models.CharField(max_length=512)),
                ('movies_url', models.CharField(blank=True, max_length=10000000, null=True)),
                ('movies_local', models.FileField(blank=True, null=True, upload_to='')),
                ('country', models.CharField(max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('add_departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_departments', to='add_all.add_departments')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('video_url', models.CharField(max_length=1024)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='add_all.add_movies')),
            ],
        ),
    ]
