# Generated by Django 5.0.7 on 2024-08-19 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='add_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_preview', models.FileField(blank=True, null=True, upload_to='movies_images')),
                ('movies_name', models.CharField(max_length=128)),
                ('movies_description', models.CharField(max_length=512)),
                ('movies_url', models.CharField(max_length=10000000)),
                ('add_departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_departments', to='add_all.add_departments')),
            ],
        ),
    ]
