# Generated by Django 4.2.17 on 2025-01-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movies',
            name='generated_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
