# Generated by Django 5.0.7 on 2024-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movies',
            name='movies_preview_url',
            field=models.CharField(default=1, max_length=5024),
            preserve_default=False,
        ),
    ]
