# Generated by Django 4.2.17 on 2024-12-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0002_remove_add_movies_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movies',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
