# Generated by Django 5.0.7 on 2024-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0002_add_movies_movies_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movies',
            name='movies_local',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='add_movies',
            name='movies_preview_url',
            field=models.CharField(blank=True, max_length=5024, null=True),
        ),
        migrations.AlterField(
            model_name='add_movies',
            name='movies_url',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
