# Generated by Django 4.2.17 on 2024-12-28 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0003_add_movies_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
