# Generated by Django 5.0.7 on 2024-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0004_add_departments_description_add_departments_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
