# Generated by Django 4.2.17 on 2024-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0005_savedfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_movies',
            name='genre',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='add_movies',
            name='year',
            field=models.CharField(default='', max_length=32),
        ),
    ]
