# Generated by Django 5.0.7 on 2024-08-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0006_add_movies_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('video_url', models.CharField(max_length=1024)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='add_all.add_movies')),
            ],
        ),
    ]
