# Generated by Django 4.2.17 on 2024-12-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0007_movieseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiperfilms',
            name='image_url',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
