# Generated by Django 4.2.17 on 2024-12-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_all', '0008_swiperfilms_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiperfilms',
            name='image_url',
            field=models.CharField(max_length=1025),
        ),
    ]
